Repository hozlucas28/C-Algorithms-Practical-Work-2025, pull requests merged in 2025-02, with the labels that each got.

#7 [feature] Play module initial implementation
  .github/workflows/ISSUE_TEMPLATE/bug_report.md
  libs/libs.cbp
  libs/list/main.c
  libs/list/main.h
  libs/macros.h
  libs/main.h
  libs/structs.h
  src/api/main.c
  src/api/main.h
  src/macros.h
  src/main.c
  src/play/main.c
  src/play/main.h
  src/play/utilities.c
  src/play/utilities.h
  src/src.cbp
  src/structs.h
Labels: enhancement

#9 [feature] Complete `createLocalRecord` function
  .gitignore
  libs/libs.cbp
  libs/list/main.c
  libs/list/main.h
  src/api/main.c
  src/api/main.h
  src/macros.h
  src/main.c
  src/play/main.c
  src/play/main.h
  src/statics/local-storage/.gitkeep
Labels: bug, enhancement

#13 [fix]: Infinite loop on enter a long string
  src/main.c
Labels: fix

#14 [fix]: Unexpected behaviour on no enter a player
  src/play/main.c
  src/play/utilities.c
Labels: fix

#15 [feature] Accept `y` as a valid input
  src/play/utilities.c
Labels: enhancement

#17 [chore] Add thunder client collection
  .vscode/extensions.json
  docs/api-collection
Labels: documentation

#20 ci: fix workflow
  .github/workflows/format-code.yml
Labels: fix

#23 [doc] Complete missing todos
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation_report.md
  .github/ISSUE_TEMPLATE/fix_report.md
  .github/ISSUE_TEMPLATE/improvement_report.md
  .github/ISSUE_TEMPLATE/todo_report.md
  README.md
  docs/statics/preview.png
  docs/statics/preview.psd
  docs/translations/es/README.md
  libs/libs.cbp
  libs/list/main.c
  libs/list/main.h
  libs/macros.h
  libs/main.h
  libs/structs.h
  libs/time/main.h
  libs/utilities.c
  libs/utilities.h
  src/main.c
  src/play/main.c
  src/src.cbp
  src/structs.h
  src/utilities.c
  src/utilities.h
Labels: documentation

#30 [feature] Improve outputs
  src/play/main.c
Labels: improvement

#22 [feature] Game logic and implementation
  src/configuration/macros.h
  src/play/main.c
  src/play/tateti/main.c
  src/play/tateti/main.h
  src/play/utilities.c
  src/play/utilities.h
  src/src.cbp
  src/structs.h
  src/utilities.c
  src/utilities.h
Labels: improvement

#31 [fix] Local record creation
  src/api/main.c
  src/api/main.h
  src/configuration/functions.c
  src/configuration/logs/main.c
  src/configuration/macros.h
  src/configuration/structs.h
  src/macros.h
  src/main.c
  src/play/main.c
  src/play/main.h
  src/play/structs.h
  src/play/tateti/main.c
  src/play/tateti/main.h
  src/show-ranking/main.c
  src/structs.h
  src/utilities.c
  src/utilities.h
Labels: fix

#33 [chore] Rename list methods
  libs/libs.cbp
  libs/list/main.c
  libs/main.h
  libs/singly-list/main.c
  libs/singly-list/main.h
  src/api/main.c
  src/api/main.h
  src/api/utilities.c
  src/api/utilities.h
  src/play/main.c
  src/play/structs.h
  src/play/tateti/main.c
  src/play/utilities.c
  src/play/utilities.h
  src/show-ranking/main.c
Labels: improvement

#35 [FIX]: Fixing input player names
  src/play/tateti/main.c
  src/play/utilities.c
  src/play/utilities.h
Labels: improvement, fix
